### ISSUE TITLE
Higher quality songs

### ISSUE THREAD

**Issue by throwawayay** [arunKumarNOP/Saavn-Downloader#1]
(I am a Saavn Pro user)

You should know that the mp3 downloaded is not actually the highest quality available. Actually there is a special server that provides true HQ:

ie. `http://aac.saavncdn.com/790/b45f26b51cb523c8da9c9a2fb575edf7_320.mp4` and `http://aac.saavncdn.com/590/3f150d88b4452f86edace617a58ee968_320.mp4` (is actually an mp3 file) - this URL is not derived from `encrypted_media_url` and is not exposed anywhere on the web interface.

**Comment by arunKumarNOP** [comment]
Ya initially i thought that the website offers highest quality audio, but after doing further analysis of the app i finally managed to get all its API and so i created a Android project for the same, the Android project is available in my repository here https://github.com/arunKumarNOP/Saavn-Downloader-Android
