### ISSUE TITLE
invalid sintax error while running python with saavn_downloader.py

### ISSUE THREAD

**Issue by abdullah5490** [arunKumarNOP/Saavn-Downloader#2]
here's what i've done:
1. install python 3.0 x64 on windows10 9fully updated).
2. open command prompt in admin mode. 
3. then navigated to the python installation directory by "cd c:\python30"
4. Then typed this command "python saavn_downloader.py", because the "saavn_downloader.py" is already placed in the "python30" folder, and got the following error message and nothing happened!
  File "saavn_downloader.py", line 5                                                                                    
    <!DOCTYPE html>                                                                                                     
    ^                                                                                                                   
SyntaxError: invalid syntax                                                                                              

How to workaround this problem? Therefore, i really appreciate your work for both windows and android OS's for downloading music.

**Comment by throwawayay** [comment]
You need BeautifulSoup4.
`pip install beautifulsoup4` or try manual install: https://groups.google.com/forum/#!topic/beautifulsoup/4zv6xibc3d0

**Comment by abdullah5490** [comment]
Ok, I did what exactly stated in your link, BS installed without any errors, but still the same error upon running saavn_downloader. Now, what to do next to get it in to  work?

**Comment by arunKumarNOP** [comment]
@abdullah5490 Line 5 is "import os" i don't know why its saying invalid syntax, once re-download the repository and then run.

**Comment by abdullah5490** [comment]
I don't know much about repository and all these things, i've just 
downloaded the "saavn_downloader.py" file from here which you've 
provided. Could you please provide me the updated file which should work?

regards,
Abdullah Zafar from Islamabad Pakistan!
CEO at
Blind Help Project <http://www.blindhelp.net>
Trainning coordinator at
Masiha Educational Welfare Society <http://www.facebook.com/masews>
Media manager at
Pakistan Paraclimbing Club <http://www.facebook.com/pakparaclimbing>
Add me on skype as Abdullah.93@outlook.com
Meet on facebook
Abdullah Zafar on facebook! <http://www.facebook.com/abdullah5490>
Or on twitter
Abdullah5490 on twitter! <http://www.twitter.com/abdullah5490>
Send from thunderbird for windows e-mail client!

**Comment by arunKumarNOP** [comment]
Once do 'git pull https://github.com/arunKumarNOP/Saavn-Downloader.git' and then run the script.

I think you copied the code which might have messed up the syntax or indentation.

**Comment by xsumirx** [comment]
wrong syntax with input function, yup I was also facing same.

Solution: change input function to raw_input, that would solve the matter.
